import { Task } from '@/types';

export function downloadPdfNotes(task: Task) {
  if (typeof window === 'undefined') return;

  // Open printable PDF preview window
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    downloadTextNotes(task);
    return;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ABTalks Day ${task.day} Lecture Notes - ${task.title}</title>
  <style>
    @media print {
      body { bg-color: #ffffff; color: #000000; }
      .no-print { display: none; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      background: #f8fafc;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      border-bottom: 3px solid #f59e0b;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .logo {
      font-size: 24px;
      font-weight: 900;
      color: #0f172a;
      letter-spacing: -0.5px;
    }
    .logo span { color: #d97706; }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 9999px;
      font-size: 12px;
      font-weight: 700;
      background: #fef3c7;
      color: #92400e;
      margin-right: 8px;
    }
    h1 { font-size: 22px; font-weight: 800; color: #0f172a; margin-top: 10px; }
    .section-title {
      font-size: 14px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #d97706;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 6px;
      margin-top: 24px;
      margin-bottom: 12px;
    }
    .notes-box {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 18px;
      font-size: 14px;
      color: #334155;
    }
    pre {
      background: #0f172a;
      color: #f8fafc;
      padding: 16px;
      border-radius: 12px;
      font-family: "Courier New", Courier, monospace;
      font-size: 13px;
      overflow-x: auto;
      white-space: pre-wrap;
    }
    ul { padding-left: 20px; font-size: 14px; color: #334155; }
    li { margin-bottom: 6px; }
    .btn-print {
      background: #d97706;
      color: white;
      border: none;
      padding: 10px 20px;
      font-size: 14px;
      font-weight: bold;
      border-radius: 8px;
      cursor: pointer;
      margin-bottom: 20px;
    }
  </style>
</head>
<body>
  <div className="no-print">
    <button onclick="window.print()" class="btn-print">🖨 Save as PDF / Print Document</button>
  </div>

  <div class="header">
    <div class="logo">ABTalks <span>2.0</span></div>
    <div>
      <span class="badge">Day ${task.day} of 60</span>
      <span class="badge">${task.category}</span>
      <span class="badge">${task.difficulty}</span>
      <span class="badge" style="background:#dcfce7; color:#166534">Score: ${task.score}/100 ⭐</span>
    </div>
    <h1>${task.title}</h1>
    <p style="color:#64748b; font-size:14px; margin-top:4px;">${task.description}</p>
  </div>

  <div class="section-title">Technical Lecture Notes</div>
  <div class="notes-box">
    ${task.notes}
  </div>

  <div class="section-title">Technical Acceptance Requirements</div>
  <ul>
    ${task.requirements.map((req) => `<li>${req}</li>`).join('')}
  </ul>

  <div class="section-title">Day-Specific Code Implementation</div>
  <pre><code>${escapeHtml(task.codeExample)}</code></pre>

  <div class="section-title">Video Lesson Metadata</div>
  <p style="font-size:14px; color:#475569;">
    <strong>Class Title:</strong> ${task.videoTitle}<br/>
    <strong>Duration:</strong> ${task.videoDuration}<br/>
    <strong>Repository:</strong> ${task.githubTemplate}
  </p>

  <div style="margin-top:40px; border-top:1px solid #e2e8f0; padding-top:16px; font-size:12px; color:#94a3b8; text-align:center;">
    Verified Technical Document • Generated by ABTalks 2.0 State Engine
  </div>

  <script>
    setTimeout(() => { window.print(); }, 500);
  </script>
</body>
</html>`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

export function downloadTextNotes(task: Task) {
  const content = `================================================================================
ABTALKS 2.0 — TECHNICAL LECTURE NOTES & CODE PROOF
================================================================================

Day ${task.day}: ${task.title}
Track Category: ${task.category}
Difficulty Tier: ${task.difficulty}
Estimated Hours: ${task.estimatedHours} Hours
Verified Performance Score: ${task.score}/100 ⭐

--------------------------------------------------------------------------------
TECHNICAL LECTURE NOTES & ARCHITECTURAL CONCEPTS
--------------------------------------------------------------------------------
${task.notes}

--------------------------------------------------------------------------------
TECHNICAL ACCEPTANCE REQUIREMENTS
--------------------------------------------------------------------------------
${task.requirements.map((req, idx) => `[ ${idx + 1} ] ${req}`).join('\n')}

--------------------------------------------------------------------------------
DAY-SPECIFIC RUNNABLE CODE EXAMPLE
--------------------------------------------------------------------------------
${task.codeExample}

--------------------------------------------------------------------------------
VIDEO LESSON CLASS
--------------------------------------------------------------------------------
Title: ${task.videoTitle}
Duration: ${task.videoDuration}
Starter Template: ${task.githubTemplate}

================================================================================
Generated on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}
ABTalks 2.0 — Built for Consistency
================================================================================`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ABTalks_Day_${task.day}_Lecture_Notes.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
